// Code generated by go-swagger; DO NOT EDIT.

// Package restapi AWS RDS Monitoring Tool (ARMT)
//
//  ARMT provides rest endpoints to help clients to get monitoring data from RDS instances in AWS cluster.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/armt
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
